#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 256371-web-01 100.26.11.65:80 check\n\tserver 256371-web-02 54.90.23.236:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
